name: stock-service

server:
  servlet:
    context-path: /ws/api/stock-service/v1
  port: 9083

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bigproject?useSSL=false
    jdbcUrl: jdbc:mysql://localhost:3306/bigproject?useSSL=false
    username: root
    password: password
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect